name: Run Scraping Code

on: 
    schedule:
    # * is a special character in YAML so you have to quote this string
    # Example: 
    #           - cron:  '30 5,17 * * *'
    #           triggers the workflow every day at 5:30 and 17:30 UTC:
    # POSIX cron syntax: https://pubs.opengroup.org/onlinepubs/9699919799/utilities/crontab.html#tag_20_25_07
    - cron:  '30 17,23 * * *' #run at 10:30am and 4:30pm pacific time

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2 #check out the repository
      - uses: r-lib/actions/setup-r@v1 #set up the R environment
      - name: Install packages #Job 1: install packages the next step will need
        run:
          Rscript -e "install.packages(c('httr', 'jsonlite', 'xml2', 'rvest','stringr','sf','readtext', 'lubridate'))"
      - name: Run Scraping Code File #Job 2: run the code that scrapes the workplace exposure site
        run:
          Rscript -e "source('code/scrape_exposure_data.R')"
      - name: install topojson
	run:
	  npm install topojson
      - name: convert to TopoJSON
	run:
	  geo2topo mapinput.geojson > mapinput.topojson
      - name: Run topojson to js code
        run:
          Rscript -e "source('code/topojson_to_js.R')"
      - name: Commit results #Job 3: commit the changes back to the repository
        run: 
	  
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git commit -a -m 'Updated scraped data' || echo "Updated scraped data"
          git push origin || echo "Pushed updated scraped data"